// JSON Schema → TypeScript commander command emitter.
//
// Input:  the GET /api/tools catalog (an array of ToolCatalogEntry)
// Output: a TS source file that exports `registerGeneratedTools(program)`
//         which registers one commander command per tool, with smart
//         flag coercion for primitives, Vector3, GameObjectRef, enums.

import type { JsonSchema, ToolCatalogEntry, FlagKind, ResolvedProperty } from './types.js';
import { resolveRef, refName, classifyRefTarget } from './refs.js';
import { normalizeToolCatalog } from '../catalog.js';

const INTEGER_BOUND_OVERRIDES: Readonly<Record<string, Readonly<Record<string, {
  minimum?: number;
  maximum?: number;
}>>>> = {
  // The current uco bridge catalog describes these bounds but does not emit
  // JSON Schema minimum/maximum keywords. Keep the CLI boundary aligned with
  // the server-side validation across catalog regeneration.
  'tests-run': {
    executionTimeoutSeconds: { minimum: 1, maximum: 86_400 },
    waitTimeoutSeconds: { minimum: 1, maximum: 300 },
  },
};

const HEADER = `// AUTO-GENERATED by uco codegen — do not edit by hand.
// Regenerate with: \`npm run gen --silent -- <unity-project-path>\`
// or programmatically via src/codegen/{fetch,emit}.ts.
//
// Source: GET /api/tools from the uco bridge (upstream lineage).
// Each tool becomes a top-level commander subcommand whose flags
// mirror its inputSchema.properties — required → .requiredOption(),
// optional → .option(), with smart coercion for Vector3 / GameObjectRef
// shorthand, enums via .choices(), and JSON for nested objects/arrays.
`;

export function emitToolCommands(tools: readonly ToolCatalogEntry[]): string {
  // Emit a command for every tool, regardless of upstream `enabled` flag.
  // The server gates invocation; uco's job is to maximize discoverability.
  // When a disabled tool is called, the server returns 4xx — the user can
  // then run `uco configure --enable-tools <name>` to switch it on.
  const catalog = normalizeToolCatalog(tools);
  const out: string[] = [];
  out.push(HEADER);
  out.push(`import { Command, Option } from 'commander';`);
  out.push(`import { runCommand } from '../util/cli-context.js';`);
  out.push(`import { addToolCallControlOptions, toolCallOptionsFromCli } from '../util/call-control.js';`);
  out.push(
    `import { coerceVec3, coerceGameObjectRef, coerceInteger, coerceNumber, coerceBoolean, coerceJson } from '../codegen/coerce.js';`,
  );
  out.push(`import { resolveTextInput } from '../util/input.js';`);
  out.push(``);
  out.push(`export const GENERATED_TOOL_NAMES: readonly string[] = [`);
  for (const t of catalog) out.push(`  ${JSON.stringify(t.name)},`);
  out.push(`];`);
  out.push(``);
  out.push(`/** Tools the server has marked disabled in its config at codegen time. */`);
  out.push(`export const DEFAULT_DISABLED_TOOLS: readonly string[] = [`);
  for (const t of catalog) {
    if (t.enabled === false) out.push(`  ${JSON.stringify(t.name)},`);
  }
  out.push(`];`);
  out.push(``);
  out.push(`export function registerGeneratedTools(program: Command): void {`);
  for (const tool of catalog) {
    out.push(emitOne(tool));
  }
  out.push(`}`);
  return out.join('\n') + '\n';
}

function emitOne(tool: ToolCatalogEntry): string {
  const props = resolveProperties(tool);
  const summary = oneLine(tool.description || tool.title || tool.name);

  const lines: string[] = [];
  lines.push(`  // ${tool.title || tool.name}`);
  lines.push(`  {`);
  lines.push(`    const cmd = program`);
  lines.push(`      .command(${JSON.stringify(tool.name)})`);
  lines.push(`      .description(${JSON.stringify(summary)});`);
  for (const p of props) {
    lines.push(emitFlag(p, tool.name === 'script-execute' && p.name === 'csharpCode'));
  }
  if (tool.name === 'script-execute') {
    lines.push(`    cmd.addOption(new Option("--code-file <path>", "Read csharpCode as strict UTF-8 from a path or - (stdin)."));`);
  }
  lines.push(`    addToolCallControlOptions(cmd);`);
  lines.push(`    cmd.action(function (this: Command, _opts: Record<string, unknown>) {`);
  lines.push(`      return runCommand(this, async (ctx) => {`);
  lines.push(`        const opts = this.opts();`);
  lines.push(`        const args: Record<string, unknown> = {};`);
  for (const p of props) {
    // Only include the parameter when the user actually passed it.
    if (tool.name === 'script-execute' && p.name === 'csharpCode') {
      lines.push(`        args["csharpCode"] = resolveTextInput(opts["csharpCode"], opts["codeFile"], "--csharpCode", "--code-file");`);
    } else {
      lines.push(`        if (opts[${JSON.stringify(p.name)}] !== undefined) args[${JSON.stringify(p.name)}] = opts[${JSON.stringify(p.name)}];`);
    }
  }
  lines.push(`        return ctx.transport.callTool(${JSON.stringify(tool.name)}, args, toolCallOptionsFromCli(opts));`);
  lines.push(`      })();`);
  lines.push(`    });`);
  lines.push(`  }`);
  return lines.join('\n');
}

function emitFlag(p: ResolvedProperty, deferRequired = false): string {
  const flag = `--${p.name} ${valueToken(p)}`;
  const desc = oneLine(p.description || p.name);
  // Build via Option so we can attach choices + parser cleanly.
  const optExpr = buildOptionExpr(flag, desc, p);
  const method = p.required ? 'addOption' : 'addOption';
  // Required: use `.makeOptionMandatory(true)` chained on the Option.
  const suffix = p.required && !deferRequired ? '.makeOptionMandatory(true)' : '';
  return `    cmd.${method}(${optExpr}${suffix});`;
}

function buildOptionExpr(flag: string, desc: string, p: ResolvedProperty): string {
  const base = `new Option(${JSON.stringify(flag)}, ${JSON.stringify(desc)})`;
  switch (p.kind) {
    case 'enum-string':
      return `${base}.choices(${JSON.stringify(p.enumValues ?? [])})`;
    case 'integer':
      return `${base}.argParser(${integerParser(p)})`;
    case 'number':
      return `${base}.argParser(coerceNumber)`;
    case 'boolean':
      return `${base}.argParser(coerceBoolean)`;
    case 'vec3':
      return `${base}.argParser(coerceVec3)`;
    case 'gameobject-ref':
      return `${base}.argParser(coerceGameObjectRef)`;
    case 'object':
    case 'array':
      return `${base}.argParser(coerceJson)`;
    case 'string':
    default:
      return base;
  }
}

function valueToken(p: ResolvedProperty): string {
  switch (p.kind) {
    case 'enum-string': return '<value>';
    case 'integer': return '<int>';
    case 'number': return '<num>';
    case 'boolean': return '<bool>';
    case 'vec3': return '<x,y,z|json>';
    case 'gameobject-ref': return '<ref>';
    case 'object': return '<json>';
    case 'array': return '<json-array>';
    case 'string':
    default: return '<string>';
  }
}

function resolveProperties(tool: ToolCatalogEntry): ResolvedProperty[] {
  const schema = asJsonSchema(tool.inputSchema);
  if (!schema || !schema.properties) return [];
  const $defs = schema.$defs ?? {};
  const required = new Set(schema.required ?? []);
  const result: ResolvedProperty[] = [];
  for (const [name, raw] of Object.entries(schema.properties)) {
    const resolved = resolveRef(raw, $defs);
    const refTarget = raw.$ref ? refName(raw) : undefined;
    const refClass = refTarget ? classifyRefTarget(refTarget) : undefined;
    const kind = pickKind(resolved, refClass);
    const enumValues = resolved.enum && Array.isArray(resolved.enum)
      ? resolved.enum.filter((v): v is string => typeof v === 'string')
      : undefined;
    const override = INTEGER_BOUND_OVERRIDES[tool.name]?.[name];
    const minimum = finiteNumber(raw.minimum ?? resolved.minimum ?? override?.minimum);
    const maximum = finiteNumber(raw.maximum ?? resolved.maximum ?? override?.maximum);
    result.push({
      name,
      required: required.has(name),
      description: resolved.description || raw.description || '',
      kind,
      ...(enumValues && enumValues.length > 0 ? { enumValues } : {}),
      ...(kind === 'integer' && minimum !== undefined ? { minimum } : {}),
      ...(kind === 'integer' && maximum !== undefined ? { maximum } : {}),
    });
  }
  return result;
}

function asJsonSchema(value: unknown): JsonSchema | undefined {
  return value !== null && typeof value === 'object' && !Array.isArray(value)
    ? value as JsonSchema
    : undefined;
}

function integerParser(property: ResolvedProperty): string {
  if (property.minimum === undefined && property.maximum === undefined) return 'coerceInteger';
  return `(raw) => coerceInteger(raw, ${property.minimum ?? 'undefined'}, ${property.maximum ?? 'undefined'})`;
}

function finiteNumber(value: number | undefined): number | undefined {
  return typeof value === 'number' && Number.isFinite(value) ? value : undefined;
}

function pickKind(schema: JsonSchema, refClass: 'vec3' | 'gameobject-ref' | undefined): FlagKind {
  if (refClass === 'vec3') return 'vec3';
  if (refClass === 'gameobject-ref') return 'gameobject-ref';
  const t = Array.isArray(schema.type) ? schema.type[0] : schema.type;
  if (t === 'string') {
    if (schema.enum && schema.enum.length > 0) return 'enum-string';
    return 'string';
  }
  if (t === 'integer') return 'integer';
  if (t === 'number') return 'number';
  if (t === 'boolean') return 'boolean';
  if (t === 'array') return 'array';
  if (t === 'object') return 'object';
  return 'object';
}

function oneLine(s: string): string {
  return s.replace(/\s+/g, ' ').trim();
}
